### ISSUE TITLE
`snack build` fails on the `snack` repository

### ISSUE THREAD

**Issue by Gabriel439** [nmattia/snack#31] opened 2018-07-24 16:10 UTC
Steps to reproduce:

```
$ git clone https://github.com/nmattia/snack.git  # Revision dde00575c5c844cf5d32ce397ad3205103c81dc0

$ cd snack

$ nix-env -f ./default.nix -iA snack-exe

$ snack build
error: unsupported argument ‘sha256’ to ‘fetchTarball’, at 0x7fd539d06478
snack:
Ran commands:
nix-build - --no-out-link --argstr specJson '{
  "owner": "NixOS",
  "repo": "nixpkgs",
  "rev": "584270e39743020d8aa056b40eea00fcaa2b595f",
  "sha256": "1p8hrz7xz73gzcqw62f3zfkmf3pkwwn1b41xzs7ayxafkmzsh0hw"
}
' --argstr lib64 "${LARGE_BASE64_STRING}" --arg snackNix ./snack.nix
which nix-build

Exception: error running: nix-build - --no-out-link --argstr specJson '{
  "owner": "NixOS",
  "repo": "nixpkgs",
  "rev": "584270e39743020d8aa056b40eea00fcaa2b595f",
  "sha256": "1p8hrz7xz73gzcqw62f3zfkmf3pkwwn1b41xzs7ayxafkmzsh0hw"
}
' --argstr lib64 "${LARGE_BASE64_STRING}" --arg snackNix ./snack.nix
exit status: 1
stderr: error: unsupported argument ‘sha256’ to ‘fetchTarball’, at 0x7fd539d06478
```

**Comment by ixmatus** [comment] 2018-07-24 16:36
I think the problem here is that `snack` expects the user to have (>=) Nix 1.12 installed. I do but ran into another issue with this self-building example:

```
$ snack build
error: getting status of '/home/parnell/Development/oss/snack/snack.nix': No such file or directory
(use '--show-trace' to show detailed location information)
snack:
Ran commands:
nix-build - --no-out-link --argstr specJson '{
  "owner": "NixOS",
  "repo": "nixpkgs",
  "rev": "584270e39743020d8aa056b40eea00fcaa2b595f",
  "sha256": "1p8hrz7xz73gzcqw62f3zfkmf3pkwwn1b41xzs7ayxafkmzsh0hw"
}
' --argstr lib64 'H4sIABNUV1sAA+09/XPbRq75WX/FVvbUUmtRsZM0N/I5rROnbjrOx8S+a298ngwtrSzGFMlHUrb1
...
```

**Comment by nmattia** [comment] 2018-07-25 20:35
@ixmatus I've opened a PR for that particular Nix 1.12 issue: #35 

@Gabriel439 @ixmatus the following should work, provided that #35 and #36 are merged (the former makes it possible to build snack with nix < 1.12 and the latter makes it possible to run a pure shell):

```
nicolas@nicolas-XPS-13-9370:~/projects/nmattia/snack$ nix-shell --pure --run 'snack run -s ./bin/snack.nix'
Missing: COMMAND

Usage: snack ([-s|--snack-nix PATH] | [-p|--package-yaml PATH]) COMMAND
nicolas@nicolas-XPS-13-9370:~/projects/nmattia/snack$ nix-shell --pure --run 'cd bin; snack run'
Missing: COMMAND

Usage: snack ([-s|--snack-nix PATH] | [-p|--package-yaml PATH]) COMMAND
```

In your case the issue is that you're not in the directory where the `snack.nix` is. Will need to work on the error reporting...

**Comment by nmattia** [comment] 2018-08-26 13:51
Considering this as fixed, feel free to reopen if you run into the issue again.

**Closed by nmattia** 2018-08-26 13:51 UTC
